name: ChatClientProtector
version: "1.0-SNAPSHOT"
author: Your Name
main: tk.knownunown.ChatClientProtector.ChatClientProtector

commands:
  chatonly:
    description: Turns on Chat Client mode.
    usage: "Usage: /<command>"
    permission: ccp.use

permissions:
  ccp.use:
    description: Allows use of Chat Client Mode
    default: true
